config/routes.rb
Rails.application.routes.draw do
  resources :crafts
  resources :collaborations
  resources :posts
  resources :projects
  root to: "projects#index"
end

app/models/craft.rb
class Craft < ApplicationRecord
  has_many_attached :photos
end

app/controllers/crafts_controller.rb
class CraftsController < ApplicationController
  before_action :set_craft, only: %i[ show edit update destroy ]

  # GET /crafts or /crafts.json
  def index
    @crafts = Craft.all
  end

  # GET /crafts/1 or /crafts/1.json
  def show
  end

  # GET /crafts/new
  def new
    @craft = Craft.new
  end

  # GET /crafts/1/edit
  def edit
  end

  # POST /crafts or /crafts.json
  def create
    @craft = Craft.new(craft_params)

    respond_to do |format|
      if @craft.save
        format.html { redirect_to craft_url(@craft), notice: "Craft was successfully created." }
        format.json { render :show, status: :created, location: @craft }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @craft.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crafts/1 or /crafts/1.json
  def update
    respond_to do |format|
      if @craft.update(craft_params)
        format.html { redirect_to craft_url(@craft), notice: "Craft was successfully updated." }
        format.json { render :show, status: :ok, location: @craft }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @craft.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crafts/1 or /crafts/1.json
  def destroy
    @craft.destroy

    respond_to do |format|
      format.html { redirect_to crafts_url, notice: "Craft was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_craft
      @craft = Craft.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def craft_params
      params.require(:craft).permit(:name, :description, photos: [])
    end
end

app/helpers/crafts_helper.rb
module CraftsHelper
end

app/views/crafts/_craft.html.erb
<div id="<%= dom_id craft %>">
  <p>
    <strong>Title:</strong>
    <%= craft.name %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= craft.description %>
  </p>

</div>

app/views/crafts/_form.html.erb
<%= form_with(model: craft, class: "contents") do |form| %>
  <% if craft.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(craft.errors.count, "error") %> prohibited this craft from being saved:</h2>

      <ul>
        <% craft.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div>
    <%= form.label :photos, "Craft Photos" %>
    <%= form.file_field :photos, multiple: true %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/crafts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing craft</h1>

  <%= render "form", craft: @craft %>

  <%= link_to "Show this craft", @craft, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to crafts", crafts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/crafts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Crafts</h1>
    <%= link_to 'New Craft', new_craft_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

   <div id="craft" class="min-w-full">
  <% @crafts.each do |craft| %>
    <%= render craft %>
    <% if craft.photos.attached? %>
      <div class="craft-photos">
        <% craft.photos.each do |photo| %>
          <%= image_tag photo %>
        <% end %>
    <% end %>
  <% end %>
  </div>
</div>
</div>

app/views/crafts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New craft</h1>

  <%= render "form", craft: @craft %>

  <%= link_to 'Back to crafts', crafts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/crafts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @craft %>
    <% if @craft.photos.attached? %>
      <div class="craft-photos">
        <% @craft.photos.each do |photo| %>
          <%= image_tag photo %>
        <% end %>
    <% end %>

    <%= link_to 'Edit this craft', edit_craft_path(@craft), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this craft', craft_path(@craft), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to crafts', crafts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>