config/routes.rb
Rails.application.routes.draw do
  resources :crafts
  resources :collaborations
  resources :posts
  resources :projects
  root to: "projects#index"
end

app/models/collaboration.rb
class Collaboration < ApplicationRecord
  has_many_attached :photos
end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController
  before_action :set_collaboration, only: %i[ show edit update destroy ]

  # GET /collaborations or /collaborations.json
  def index
    @collaborations = Collaboration.all
  end

  # GET /collaborations/1 or /collaborations/1.json
  def show
  end

  # GET /collaborations/new
  def new
    @collaboration = Collaboration.new
  end

  # GET /collaborations/1/edit
  def edit
  end

  # POST /collaborations or /collaborations.json
  def create
    @collaboration = Collaboration.new(collaboration_params)

    respond_to do |format|
      if @collaboration.save
        format.html { redirect_to collaboration_url(@collaboration), notice: "Collaboration was successfully created." }
        format.json { render :show, status: :created, location: @collaboration }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @collaboration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collaborations/1 or /collaborations/1.json
  def update
    respond_to do |format|
      if @collaboration.update(collaboration_params)
        format.html { redirect_to collaboration_url(@collaboration), notice: "Collaboration was successfully updated." }
        format.json { render :show, status: :ok, location: @collaboration }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @collaboration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collaborations/1 or /collaborations/1.json
  def destroy
    @collaboration.destroy

    respond_to do |format|
      format.html { redirect_to collaborations_url, notice: "Collaboration was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collaboration
      @collaboration = Collaboration.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def collaboration_params
      params.require(:collaboration).permit(:name, :description, photos: [])
    end
end

app/helpers/collaborations_helper.rb
module CollaborationsHelper
end

app/views/collaborations/_collaboration.html.erb
<div id="<%= dom_id collaboration %>">
  <p>
    <strong>Name:</strong>
    <%= collaboration.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= collaboration.description %>
  </p>

</div>

app/views/collaborations/_form.html.erb
<%= form_with(model: collaboration, class: "contents") do |form| %>
  <% if collaboration.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(collaboration.errors.count, "error") %> prohibited this collaboration from being saved:</h2>

      <ul>
        <% collaboration.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div>
    <%= form.label :photos, "Project Photos" %>
    <%= form.file_field :photos, multiple: true %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/collaborations/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing collaboration</h1>

  <%= render "form", collaboration: @collaboration %>

  <%= link_to "Show this collaboration", @collaboration, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to collaborations", collaborations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/collaborations/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Collaboration</h1>
    <%= link_to 'New Post', new_collaboration_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

   <div id="post" class="min-w-full">
    <% @collaborations.each do |collaboration| %>
      <%= render collaboration %>
        <% if collaboration.photos.attached? %>
          <div class="post-photos">
            <% collaboration.photos.each do |photo| %>
              <%= image_tag photo %>
            <% end %>
        <% end %>
    <% end %>
  </div>
</div>
</div>

app/views/collaborations/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New collaboration</h1>

  <%= render "form", collaboration: @collaboration %>

  <%= link_to 'Back to collaborations', collaborations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/collaborations/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @collaboration %>
    <% if @collaboration.photos.attached? %>
      <div class="project-photos">
        <% @collaboration.photos.each do |photo| %>
          <%= image_tag photo %>
        <% end %>
    <% end %>

    <%= link_to 'Edit this collaboration', edit_collaboration_path(@collaboration), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this collaboration', collaboration_path(@collaboration), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to collaborations', collaborations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>